Repository CodeDead/DeadHash-android, pull requests merged in 2022-03, with the labels that each got.

#15 Feature/upgrades
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: enhancement

#14 RU translation
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: translation

#16 feature/translations
  app/src/main/java/com/codedead/deadhash/gui/MainActivity.java
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#18 Release/v1.7.6
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codedead/deadhash/gui/MainActivity.java
  app/src/main/res/layout/content_about.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, translation

#19 * Fixed version code
  app/build.gradle
Labels: bug

#20 feature/translation-fixes
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
Labels: translation
